site:
  name: Moxin AI
  logoAlt: "Moxin LLM Company Logo"
  site: 'https://moxin-ai.org'      # CORRECTED: Your actual custom domain
  base: '/'                 # CORRECTED: Set to root path as you're using a custom domain at the root
  trailingSlash: true

  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

# Default SEO metadata
metadata:
  title:
    default: Moxin AI
    template: '%s — Moxin AI'
  description: "🚀 Moxin AI: Truly Open, Fully Reproducible AI. High-performance language models for edge devices and research."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Moxin AI
    type: website
  twitter:
    handle: '@moxin_org'
    site: '@moxin_org'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/blog/%slug%'
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog'
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category'
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag'
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: 'light'