site:
  name: Moxin LLM
  logoAlt: "Moxin LLM Company Logo"
  site: 'https://moxin-org.github.io'      # CORRECTED: Your actual domain
  base: '/moxin-llm-web/'                 # CORRECTED: Your repository name / base path
  trailingSlash: false                    # This can usually stay as is

  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

# Default SEO metadata
metadata:
  title:
    default: Moxin LLM
    template: '%s — Moxin LLM'
  description: "🚀 Moxin LLM: Truly Open, Fully Reproducible AI. High-performance language models for edge devices and research." # Consider updating your description too
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Moxin LLM # This is good
    type: website
    # It's a good practice to also set a default og:image here if your theme supports it
  twitter:
    handle: '@moxin_org' # UPDATE if you have a specific X/Twitter handle for Moxin
    site: '@moxin_org'   # UPDATE if you have a specific X/Twitter handle for Moxin
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/blog/%slug%' # Adjusted permalink to be nested under blog
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' 
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category' 
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag' 
      robots:
        index: false # Usually, tag pages are not indexed to avoid duplicate content issues, this is fine.

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null 

ui:
  theme: 'system'